### PR TITLE
autoinit nested selects

### PR DESCRIPTION
**Pull request by Hamper**
autoinit for inserts like ```<div><select>...</select></div>``` and fix multiselect init

### CODE REVIEW

**Comment by FezVrasta** [comment]
nested selects?

**Comment by Hamper** [comment]
for some inserts like ```<div><select>...</select></div>``` DOMNodeInserted event generated only for outer div but not for select (I checked it in firefox)

**Comment by FezVrasta** [comment]
What if I triple nest the select element?

**Comment by Hamper** [comment]
.find('select') in my patch will find all selects regardless of nesting

**Pull request merged**
